package edu.ualberta.med.biobank.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * StudyEventAttr generated by hbm2java
 */
@Entity
@Table(name = "STUDY_EVENT_ATTR")
public class StudyEventAttr extends AbstractBiobankModel {
    private static final long serialVersionUID = 1L;

    private String permissible;
    private boolean required;
    private GlobalEventAttr globalEventAttr;
    private Study study;
    private ActivityStatus activityStatus;

    @Column(name = "PERMISSIBLE")
    public String getPermissible() {
        return this.permissible;
    }

    public void setPermissible(String permissible) {
        this.permissible = permissible;
    }

    @Column(name = "REQUIRED")
    // TODO: rename to isRequired
    public boolean getRequired() {
        return this.required;
    }

    public void setRequired(boolean required) {
        this.required = required;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "GLOBAL_EVENT_ATTR_ID", nullable = false)
    public GlobalEventAttr getGlobalEventAttr() {
        return this.globalEventAttr;
    }

    public void setGlobalEventAttr(GlobalEventAttr globalEventAttr) {
        this.globalEventAttr = globalEventAttr;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "STUDY_ID", nullable = false)
    public Study getStudy() {
        return this.study;
    }

    public void setStudy(Study study) {
        this.study = study;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ACTIVITY_STATUS_ID", nullable = false)
    public ActivityStatus getActivityStatus() {
        return this.activityStatus;
    }

    public void setActivityStatus(ActivityStatus activityStatus) {
        this.activityStatus = activityStatus;
    }
}
