INSERT INTO `revision`
  SET ID = 0, COMMITTED_AT = UNIX_TIMESTAMP(NOW()) * 1000, GENERATED_AT = UNIX_TIMESTAMP(NOW()) * 1000, REVISION_TIMESTAMP = UNIX_TIMESTAMP(NOW()) * 1000;
   

INSERT INTO `address_audit` (REVISION_ID, REVISION_TYPE, ID, 
    CITY, COUNTRY, EMAIL_ADDRESS, FAX_NUMBER, PHONE_NUMBER, POSTAL_CODE, PROVINCE, STREET1, STREET2)
  SELECT 0, 0, ID,
    CITY, COUNTRY, EMAIL_ADDRESS, FAX_NUMBER, PHONE_NUMBER, POSTAL_CODE, PROVINCE, STREET1, STREET2
    FROM `address`;

INSERT INTO `center_audit` (REVISION_ID, REVISION_TYPE, ID,
    DISCRIMINATOR, ACTIVITY_STATUS_ID, NAME, NAME_SHORT, ADDRESS_ID, SENDS_SHIPMENTS, STUDY_ID)
  SELECT 0, 0, ID,
    DISCRIMINATOR, ACTIVITY_STATUS_ID, NAME, NAME_SHORT, ADDRESS_ID, SENDS_SHIPMENTS, STUDY_ID
    FROM `center`;

INSERT INTO `center_comment_audit` (REVISION_ID, REVISION_TYPE,
    CENTER_ID, COMMENT_ID)
  SELECT 0, 0,
    CENTER_ID, COMMENT_ID
    FROM `center_comment`;

INSERT INTO `center_origininfo_audit` (REVISION_ID, REVISION_TYPE,
    CENTER_ID, ID)
  SELECT 0, 0,
    CENTER_ID, ID
    FROM `origin_info`;

INSERT INTO `collection_event_audit` (REVISION_ID, REVISION_TYPE, ID,
    ACTIVITY_STATUS_ID, VISIT_NUMBER, PATIENT_ID)
  SELECT 0, 0, ID,
    ACTIVITY_STATUS_ID, VISIT_NUMBER, PATIENT_ID
    FROM `collection_event`;

INSERT INTO `collection_event_comment_audit` (REVISION_ID, REVISION_TYPE,
    COLLECTION_EVENT_ID, COMMENT_ID)
  SELECT 0, 0,
    COLLECTION_EVENT_ID, COMMENT_ID
    FROM `collection_event_comment`;

INSERT INTO `comment_audit` (REVISION_ID, REVISION_TYPE, ID,
    CREATED_AT, MESSAGE)
  SELECT 0, 0, ID,
    CREATED_AT, MESSAGE
    FROM `comment`;

INSERT INTO `contact_audit` (REVISION_ID, REVISION_TYPE, ID,
    EMAIL_ADDRESS, FAX_NUMBER, MOBILE_NUMBER, NAME, OFFICE_NUMBER, PAGER_NUMBER, TITLE, CLINIC_ID)
  SELECT 0, 0, ID,
    EMAIL_ADDRESS, FAX_NUMBER, MOBILE_NUMBER, NAME, OFFICE_NUMBER, PAGER_NUMBER, TITLE, CLINIC_ID
    FROM `contact`;

INSERT INTO `container_audit` (REVISION_ID, REVISION_TYPE, ID,
    ACTIVITY_STATUS_ID, LABEL, `PATH`, PRODUCT_BARCODE, TEMPERATURE, CONTAINER_TYPE_ID, SITE_ID, TOP_CONTAINER_ID)
  SELECT 0, 0, ID,
    ACTIVITY_STATUS_ID, LABEL, `PATH`, PRODUCT_BARCODE, TEMPERATURE, CONTAINER_TYPE_ID, SITE_ID, TOP_CONTAINER_ID
    FROM `container`;

INSERT INTO `container_comment_audit` (REVISION_ID, REVISION_TYPE,
    CONTAINER_ID, COMMENT_ID)
  SELECT 0, 0,
    CONTAINER_ID, COMMENT_ID
    FROM `container_comment`;

INSERT INTO `container_position_audit` (REVISION_ID, REVISION_TYPE, ID,
    `COL`, `ROW`, CONTAINER_ID, CONTAINER_TYPE_ID, PARENT_CONTAINER_ID, PARENT_CONTAINER_TYPE_ID)
  SELECT 0, 0, ID,
    `COL`, `ROW`, CONTAINER_ID, CONTAINER_TYPE_ID, PARENT_CONTAINER_ID, PARENT_CONTAINER_TYPE_ID
    FROM `container_position`;

INSERT INTO `container_type_audit` (REVISION_ID, REVISION_TYPE, ID,
    ACTIVITY_STATUS_ID, COL_CAPACITY, ROW_CAPACITY, DEFAULT_TEMPERATURE, NAME, NAME_SHORT, TOP_LEVEL, SITE_ID)
  SELECT 0, 0, ID,
    ACTIVITY_STATUS_ID, COL_CAPACITY, ROW_CAPACITY, DEFAULT_TEMPERATURE, NAME, NAME_SHORT, TOP_LEVEL, SITE_ID
    FROM `container_type`;

INSERT INTO `container_type_comment_audit` (REVISION_ID, REVISION_TYPE,
    CONTAINER_TYPE_ID, COMMENT_ID)
  SELECT 0, 0,
    CONTAINER_TYPE_ID, COMMENT_ID
    FROM `container_type_comment`;

INSERT INTO `container_type_container_type_audit` (REVISION_ID, REVISION_TYPE,
    PARENT_CONTAINER_TYPE_ID, CHILD_CONTAINER_TYPE_ID)
  SELECT 0, 0,
    PARENT_CONTAINER_TYPE_ID, CHILD_CONTAINER_TYPE_ID
    FROM `container_type_container_type`;

INSERT INTO `dispatch_audit` (REVISION_ID, REVISION_TYPE, ID,
    STATE, RECEIVER_CENTER_ID, SENDER_CENTER_ID, SHIPMENT_INFO_ID)
  SELECT 0, 0, ID,
    STATE, RECEIVER_CENTER_ID, SENDER_CENTER_ID, SHIPMENT_INFO_ID
    FROM `dispatch`;

INSERT INTO `dispatch_comment_audit` (REVISION_ID, REVISION_TYPE,
    DISPATCH_ID, COMMENT_ID)
  SELECT 0, 0,
    DISPATCH_ID, COMMENT_ID
    FROM `dispatch_comment`;

INSERT INTO `dispatch_specimen_audit` (REVISION_ID, REVISION_TYPE, ID,
    STATE, DISPATCH_ID, SPECIMEN_ID)
  SELECT 0, 0, ID,
    STATE, DISPATCH_ID, SPECIMEN_ID
    FROM `dispatch_specimen`;

INSERT INTO `dispatch_specimen_comment_audit` (REVISION_ID, REVISION_TYPE,
    DISPATCH_SPECIMEN_ID, COMMENT_ID)
  SELECT 0, 0,
    DISPATCH_SPECIMEN_ID, COMMENT_ID
    FROM `dispatch_specimen_comment`;

INSERT INTO `event_attr_audit` (REVISION_ID, REVISION_TYPE, ID,
    `VALUE`, COLLECTION_EVENT_ID, STUDY_EVENT_ATTR_ID)
  SELECT 0, 0, ID,
    `VALUE`, COLLECTION_EVENT_ID, STUDY_EVENT_ATTR_ID
    FROM `event_attr`;

INSERT INTO `global_event_attr_audit` (REVISION_ID, REVISION_TYPE, ID,
    LABEL)
  SELECT 0, 0, ID,
    LABEL
    FROM `global_event_attr`;

INSERT INTO `origin_info_audit` (REVISION_ID, REVISION_TYPE, ID,
    CENTER_ID, RECEIVER_SITE_ID, SHIPMENT_INFO_ID)
  SELECT 0, 0, ID,
    CENTER_ID, RECEIVER_SITE_ID, SHIPMENT_INFO_ID
    FROM `origin_info`;

INSERT INTO `origin_info_comment_audit` (REVISION_ID, REVISION_TYPE,
    ORIGIN_INFO_ID, COMMENT_ID)
  SELECT 0, 0,
    ORIGIN_INFO_ID, COMMENT_ID
    FROM `origin_info_comment`;

INSERT INTO `patient_audit` (REVISION_ID, REVISION_TYPE, ID,
    CREATED_AT, PNUMBER, STUDY_ID)
  SELECT 0, 0, ID,
    CREATED_AT, PNUMBER, STUDY_ID
    FROM `patient`;

INSERT INTO `patient_comment_audit` (REVISION_ID, REVISION_TYPE,
    PATIENT_ID, COMMENT_ID)
  SELECT 0, 0,
    PATIENT_ID, COMMENT_ID
    FROM `patient_comment`;

INSERT INTO `processing_event_audit` (REVISION_ID, REVISION_TYPE, ID,
    ACTIVITY_STATUS_ID, CREATED_AT, WORKSHEET, CENTER_ID)
  SELECT 0, 0, ID,
    ACTIVITY_STATUS_ID, CREATED_AT, WORKSHEET, CENTER_ID
    FROM `processing_event`;

INSERT INTO `processing_event_comment_audit` (REVISION_ID, REVISION_TYPE,
    PROCESSING_EVENT_ID, COMMENT_ID)
  SELECT 0, 0,
    PROCESSING_EVENT_ID, COMMENT_ID
    FROM `processing_event_comment`;

INSERT INTO `request_audit` (REVISION_ID, REVISION_TYPE, ID,
    CREATED, SUBMITTED, ADDRESS_ID, RESEARCH_GROUP_ID)
  SELECT 0, 0, ID,
    CREATED, SUBMITTED, ADDRESS_ID, RESEARCH_GROUP_ID
    FROM `request`;

INSERT INTO `request_dispatch_audit` (REVISION_ID, REVISION_TYPE,
    REQUEST_ID, ID)
  SELECT 0, 0,
    REQUEST_ID, ID
    FROM `dispatch`;

INSERT INTO `request_specimen_audit` (REVISION_ID, REVISION_TYPE, ID,
    CLAIMED_BY, STATE, REQUEST_ID, SPECIMEN_ID)
  SELECT 0, 0, ID,
    CLAIMED_BY, STATE, REQUEST_ID, SPECIMEN_ID
    FROM `request_specimen`;

INSERT INTO `researchgroup_request_audit` (REVISION_ID, REVISION_TYPE,
    RESEARCH_GROUP_ID, ID)
  SELECT 0, 0,
    RESEARCH_GROUP_ID, ID
    FROM `request`;

INSERT INTO `shipment_info_audit` (REVISION_ID, REVISION_TYPE, ID,
    BOX_NUMBER, PACKED_AT, RECEIVED_AT, WAYBILL, SHIPPING_METHOD_ID)
  SELECT 0, 0, ID,
    BOX_NUMBER, PACKED_AT, RECEIVED_AT, WAYBILL, SHIPPING_METHOD_ID
    FROM `shipment_info`;

INSERT INTO `shipping_method_audit` (REVISION_ID, REVISION_TYPE, ID,
    NAME)
  SELECT 0, 0, ID,
    NAME
    FROM `shipping_method`;

INSERT INTO `site_study_audit` (REVISION_ID, REVISION_TYPE,
    SITE_ID, STUDY_ID)
  SELECT 0, 0,
    SITE_ID, STUDY_ID
    FROM `site_study`;

INSERT INTO `specimen_audit` (REVISION_ID, REVISION_TYPE, ID,
    ACTIVITY_STATUS_ID, CREATED_AT, INVENTORY_ID, QUANTITY, COLLECTION_EVENT_ID, CURRENT_CENTER_ID, ORIGIN_INFO_ID, ORIGINAL_COLLECTION_EVENT_ID, PARENT_SPECIMEN_ID, PROCESSING_EVENT_ID, TOP_SPECIMEN_ID)
  SELECT 0, 0, ID,
    ACTIVITY_STATUS_ID, CREATED_AT, INVENTORY_ID, QUANTITY, COLLECTION_EVENT_ID, CURRENT_CENTER_ID, ORIGIN_INFO_ID, ORIGINAL_COLLECTION_EVENT_ID, PARENT_SPECIMEN_ID, PROCESSING_EVENT_ID, TOP_SPECIMEN_ID
    FROM `specimen`;

INSERT INTO `specimen_comment_audit` (REVISION_ID, REVISION_TYPE,
    SPECIMEN_ID, COMMENT_ID)
  SELECT 0, 0,
    SPECIMEN_ID, COMMENT_ID
    FROM `specimen_comment`;

INSERT INTO `specimen_position_audit` (REVISION_ID, REVISION_TYPE, ID,
    `COL`, `ROW`, `POSITION_STRING`, `CONTAINER_ID`, `SPECIMEN_ID`)
  SELECT 0, 0, ID,
    `COL`, `ROW`, `POSITION_STRING`, `CONTAINER_ID`, `SPECIMEN_ID`
    FROM `specimen_position`;

INSERT INTO `study_audit` (REVISION_ID, REVISION_TYPE, ID,
    ACTIVITY_STATUS_ID, NAME, NAME_SHORT)
  SELECT 0, 0, ID,
    ACTIVITY_STATUS_ID, NAME, NAME_SHORT
    FROM `study`;

INSERT INTO `study_comment_audit` (REVISION_ID, REVISION_TYPE,
    STUDY_ID, COMMENT_ID)
  SELECT 0, 0,
    STUDY_ID, COMMENT_ID
    FROM `study_comment`;

INSERT INTO `study_contact_audit` (REVISION_ID, REVISION_TYPE,
    STUDY_ID, CONTACT_ID)
  SELECT 0, 0,
    STUDY_ID, CONTACT_ID
    FROM `study_contact`;

INSERT INTO `study_event_attr_audit` (REVISION_ID, REVISION_TYPE, ID,
    ACTIVITY_STATUS_ID, PERMISSIBLE, REQUIRED, GLOBAL_EVENT_ATTR_ID, STUDY_ID)
  SELECT 0, 0, ID,
    ACTIVITY_STATUS_ID, PERMISSIBLE, REQUIRED, GLOBAL_EVENT_ATTR_ID, STUDY_ID
    FROM `study_event_attr`;
