alter table CSM_FILTER_CLAUSE drop foreign key FK312BB93466E94C94;
alter table CSM_GROUP drop foreign key FKB55CD7D66E94C94;
alter table CSM_PG_PE drop foreign key FKBCFDC5B14A51C81;
alter table CSM_PG_PE drop foreign key FKBCFDC5BE11DC1A1;
alter table CSM_PROTECTION_ELEMENT drop foreign key FKD0D6A11866E94C94;
alter table CSM_PROTECTION_GROUP drop foreign key FKE5F7539B66E94C94;
alter table CSM_PROTECTION_GROUP drop foreign key FKE5F7539BF01DB96C;
alter table CSM_ROLE drop foreign key FKDF5A4D9866E94C94;
alter table CSM_ROLE_PRIVILEGE drop foreign key FK17BC30AA65793374;
alter table CSM_ROLE_PRIVILEGE drop foreign key FK17BC30AAA7BCDA60;
alter table CSM_USER_GROUP drop foreign key FKC901F48D4CE79E40;
alter table CSM_USER_GROUP drop foreign key FKC901F48D7D5235B4;
alter table CSM_USER_GROUP_ROLE_PG drop foreign key FK24EC58AEA7BCDA60;
alter table CSM_USER_GROUP_ROLE_PG drop foreign key FK24EC58AE14A51C81;
alter table CSM_USER_GROUP_ROLE_PG drop foreign key FK24EC58AE4CE79E40;
alter table CSM_USER_GROUP_ROLE_PG drop foreign key FK24EC58AE7D5235B4;
alter table CSM_USER_PE drop foreign key FK72D672874CE79E40;
alter table CSM_USER_PE drop foreign key FK72D67287E11DC1A1;
drop table if exists CSM_APPLICATION;
drop table if exists CSM_FILTER_CLAUSE;
drop table if exists CSM_GROUP;
drop table if exists CSM_PG_PE;
drop table if exists CSM_PRIVILEGE;
drop table if exists CSM_PROTECTION_ELEMENT;
drop table if exists CSM_PROTECTION_GROUP;
drop table if exists CSM_ROLE;
drop table if exists CSM_ROLE_PRIVILEGE;
drop table if exists CSM_USER;
drop table if exists CSM_USER_GROUP;
drop table if exists CSM_USER_GROUP_ROLE_PG;
drop table if exists CSM_USER_PE;
create table CSM_APPLICATION (APPLICATION_ID bigint not null auto_increment, APPLICATION_NAME varchar(255), APPLICATION_DESCRIPTION varchar(200), ACTIVE_FLAG tinyint not null, DECLARATIVE_FLAG tinyint not null, UPDATE_DATE date not null, DATABASE_URL varchar(100), DATABASE_USER_NAME varchar(100), DATABASE_PASSWORD varchar(100), DATABASE_DIALECT varchar(100), DATABASE_DRIVER varchar(100), primary key (APPLICATION_ID));
create table CSM_FILTER_CLAUSE (FILTER_CLAUSE_ID bigint not null auto_increment, CLASS_NAME varchar(100) not null, FILTER_CHAIN text not null, TARGET_CLASS_NAME varchar(100) not null, TARGET_CLASS_ATTRIBUTE_NAME varchar(100) not null, TARGET_CLASS_ATTRIBUTE_TYPE varchar(100) not null, TARGET_CLASS_ALIAS varchar(100), TARGET_CLASS_ATTRIBUTE_ALIAS varchar(100), GENERATED_SQL_USER text not null, GENERATED_SQL_GROUP text not null, UPDATE_DATE date, APPLICATION_ID bigint, primary key (FILTER_CLAUSE_ID));
create table CSM_GROUP (GROUP_ID bigint not null auto_increment, GROUP_NAME varchar(255), GROUP_DESC varchar(200), UPDATE_DATE date, APPLICATION_ID bigint, primary key (GROUP_ID));
create table CSM_PG_PE (PG_PE_ID bigint not null, UPDATE_DATE date, PROTECTION_ELEMENT_ID bigint, PROTECTION_GROUP_ID bigint, primary key (protection_element_id, protection_group_id));
create table CSM_PRIVILEGE (PRIVILEGE_ID bigint not null auto_increment, PRIVILEGE_NAME varchar(100) not null, PRIVILEGE_DESCRIPTION varchar(200), UPDATE_DATE date not null, primary key (PRIVILEGE_ID));
create table CSM_PROTECTION_ELEMENT (PROTECTION_ELEMENT_ID bigint not null auto_increment, PROTECTION_ELEMENT_NAME varchar(100) not null, PROTECTION_ELEMENT_DESCRIPTION varchar(200), OBJECT_ID varchar(100) not null, ATTRIBUTE varchar(100), ATTRIBUTE_VALUE varchar(100), PROTECTION_ELEMENT_TYPE varchar(100), UPDATE_DATE date not null, APPLICATION_ID bigint, primary key (PROTECTION_ELEMENT_ID));
create table CSM_PROTECTION_GROUP (PROTECTION_GROUP_ID bigint not null auto_increment, PROTECTION_GROUP_NAME varchar(100) not null, PROTECTION_GROUP_DESCRIPTION varchar(200), LARGE_ELEMENT_COUNT_FLAG tinyint not null, UPDATE_DATE date not null, PARENT_PROTECTION_GROUP_ID bigint, APPLICATION_ID bigint, primary key (PROTECTION_GROUP_ID));
create table CSM_ROLE (ROLE_ID bigint not null auto_increment, ROLE_NAME varchar(100) not null, ROLE_DESCRIPTION varchar(200), ACTIVE_FLAG tinyint not null, UPDATE_DATE date, APPLICATION_ID bigint, primary key (ROLE_ID));
create table CSM_ROLE_PRIVILEGE (ROLE_PRIVILEGE_ID bigint not null, PRIVILEGE_ID bigint, ROLE_ID bigint, primary key (role_id, privilege_id));
create table CSM_USER (USER_ID bigint not null auto_increment, LOGIN_NAME text not null, PREMGRT_LOGIN_NAME varchar(100), FIRST_NAME varchar(100) not null, LAST_NAME varchar(100) not null, ORGANIZATION varchar(100), DEPARTMENT varchar(100), TITLE varchar(100), PHONE_NUMBER varchar(15), PASSWORD varchar(100), EMAIL_ID varchar(100), START_DATE date, END_DATE date, UPDATE_DATE date not null, MIGRATED_FLAG tinyint not null, primary key (USER_ID));
create table CSM_USER_GROUP (USER_GROUP_ID bigint not null, GROUP_ID bigint, USER_ID bigint, primary key (user_id, group_id));
create table CSM_USER_GROUP_ROLE_PG (USER_GROUP_ROLE_PG_ID bigint not null auto_increment, UPDATE_DATE date not null, GROUP_ID bigint, USER_ID bigint, PROTECTION_GROUP_ID bigint, ROLE_ID bigint, primary key (USER_GROUP_ROLE_PG_ID));
create table CSM_USER_PE (USER_PROTECTION_ELEMENT_ID bigint not null, PROTECTION_ELEMENT_ID bigint, USER_ID bigint, primary key (protection_element_id, user_id));
alter table CSM_FILTER_CLAUSE add index FK312BB93466E94C94 (APPLICATION_ID), add constraint FK312BB93466E94C94 foreign key (APPLICATION_ID) references CSM_APPLICATION (APPLICATION_ID);
alter table CSM_GROUP add index FKB55CD7D66E94C94 (APPLICATION_ID), add constraint FKB55CD7D66E94C94 foreign key (APPLICATION_ID) references CSM_APPLICATION (APPLICATION_ID);
alter table CSM_PG_PE add index FKBCFDC5B14A51C81 (PROTECTION_GROUP_ID), add constraint FKBCFDC5B14A51C81 foreign key (PROTECTION_GROUP_ID) references CSM_PROTECTION_GROUP (PROTECTION_GROUP_ID);
alter table CSM_PG_PE add index FKBCFDC5BE11DC1A1 (PROTECTION_ELEMENT_ID), add constraint FKBCFDC5BE11DC1A1 foreign key (PROTECTION_ELEMENT_ID) references CSM_PROTECTION_ELEMENT (PROTECTION_ELEMENT_ID);
alter table CSM_PROTECTION_ELEMENT add index FKD0D6A11866E94C94 (APPLICATION_ID), add constraint FKD0D6A11866E94C94 foreign key (APPLICATION_ID) references CSM_APPLICATION (APPLICATION_ID);
alter table CSM_PROTECTION_GROUP add index FKE5F7539B66E94C94 (APPLICATION_ID), add constraint FKE5F7539B66E94C94 foreign key (APPLICATION_ID) references CSM_APPLICATION (APPLICATION_ID);
alter table CSM_PROTECTION_GROUP add index FKE5F7539BF01DB96C (PARENT_PROTECTION_GROUP_ID), add constraint FKE5F7539BF01DB96C foreign key (PARENT_PROTECTION_GROUP_ID) references CSM_PROTECTION_GROUP (PROTECTION_GROUP_ID);
alter table CSM_ROLE add index FKDF5A4D9866E94C94 (APPLICATION_ID), add constraint FKDF5A4D9866E94C94 foreign key (APPLICATION_ID) references CSM_APPLICATION (APPLICATION_ID);
alter table CSM_ROLE_PRIVILEGE add index FK17BC30AA65793374 (PRIVILEGE_ID), add constraint FK17BC30AA65793374 foreign key (PRIVILEGE_ID) references CSM_PRIVILEGE (PRIVILEGE_ID);
alter table CSM_ROLE_PRIVILEGE add index FK17BC30AAA7BCDA60 (ROLE_ID), add constraint FK17BC30AAA7BCDA60 foreign key (ROLE_ID) references CSM_ROLE (ROLE_ID);
alter table CSM_USER_GROUP add index FKC901F48D4CE79E40 (USER_ID), add constraint FKC901F48D4CE79E40 foreign key (USER_ID) references CSM_USER (USER_ID);
alter table CSM_USER_GROUP add index FKC901F48D7D5235B4 (GROUP_ID), add constraint FKC901F48D7D5235B4 foreign key (GROUP_ID) references CSM_GROUP (GROUP_ID);
alter table CSM_USER_GROUP_ROLE_PG add index FK24EC58AEA7BCDA60 (ROLE_ID), add constraint FK24EC58AEA7BCDA60 foreign key (ROLE_ID) references CSM_ROLE (ROLE_ID);
alter table CSM_USER_GROUP_ROLE_PG add index FK24EC58AE14A51C81 (PROTECTION_GROUP_ID), add constraint FK24EC58AE14A51C81 foreign key (PROTECTION_GROUP_ID) references CSM_PROTECTION_GROUP (PROTECTION_GROUP_ID);
alter table CSM_USER_GROUP_ROLE_PG add index FK24EC58AE4CE79E40 (USER_ID), add constraint FK24EC58AE4CE79E40 foreign key (USER_ID) references CSM_USER (USER_ID);
alter table CSM_USER_GROUP_ROLE_PG add index FK24EC58AE7D5235B4 (GROUP_ID), add constraint FK24EC58AE7D5235B4 foreign key (GROUP_ID) references CSM_GROUP (GROUP_ID);
alter table CSM_USER_PE add index FK72D672874CE79E40 (USER_ID), add constraint FK72D672874CE79E40 foreign key (USER_ID) references CSM_USER (USER_ID);
alter table CSM_USER_PE add index FK72D67287E11DC1A1 (PROTECTION_ELEMENT_ID), add constraint FK72D67287E11DC1A1 foreign key (PROTECTION_ELEMENT_ID) references CSM_PROTECTION_ELEMENT (PROTECTION_ELEMENT_ID);
