/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.ualberta.med.biobank.scanlib;

class ScanLibWin32WrapperJNI {
  public final static native int slIsTwainAvailable();
  public final static native int slSelectSourceAsDefault();
  public final static native int slConfigScannerBrightness(int jarg1);
  public final static native int slConfigScannerContrast(int jarg1);
  public final static native int slConfigPlateFrame(long jarg1, double jarg2, double jarg3, double jarg4, double jarg5);
  public final static native int slScanImage(long jarg1, double jarg2, double jarg3, double jarg4, double jarg5, String jarg6);
  public final static native int slScanPlate(long jarg1, long jarg2, String jarg3);
  public final static native int slCalibrateToPlate(long jarg1, long jarg2);
  public final static native int slDecodePlate(long jarg1, long jarg2);
  public final static native int slDecodeImage(long jarg1, String jarg2);
}
