/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.ualberta.med.biobank.scanlib;

public class ScanLib {
  public static int slIsTwainAvailable() {
    return ScanLibJNI.slIsTwainAvailable();
  }

  public static int slSelectSourceAsDefault() {
    return ScanLibJNI.slSelectSourceAsDefault();
  }

  public static int slConfigScannerBrightness(int brightness) {
    return ScanLibJNI.slConfigScannerBrightness(brightness);
  }

  public static int slConfigScannerContrast(int contrast) {
    return ScanLibJNI.slConfigScannerContrast(contrast);
  }

  public static int slConfigPlateFrame(long plateNum, double left, double top, double right, double bottom) {
    return ScanLibJNI.slConfigPlateFrame(plateNum, left, top, right, bottom);
  }

  public static int slScanImage(long dpi, double left, double top, double right, double bottom, String filename) {
    return ScanLibJNI.slScanImage(dpi, left, top, right, bottom, filename);
  }

  public static int slScanPlate(long dpi, long plateNum, String filename) {
    return ScanLibJNI.slScanPlate(dpi, plateNum, filename);
  }

  public static int slCalibrateToPlate(long dpi, long plateNum) {
    return ScanLibJNI.slCalibrateToPlate(dpi, plateNum);
  }

  public static int slDecodePlate(long dpi, long plateNum) {
    return ScanLibJNI.slDecodePlate(dpi, plateNum);
  }

  public static int slDecodeImage(long plateNum, String filename) {
    return ScanLibJNI.slDecodeImage(plateNum, filename);
  }

}
