                  <!-- application ftr begins -->                  
                  <table summary="" cellpadding="0" cellspacing="0" border="0" width="100%">
                    <tr>
                      <td align="center" height="20" class="footerMenuItem" onmouseover="changeMenuStyle(this,'footerMenuItemOver'),showCursor()" onmouseout="changeMenuStyle(this,'footerMenuItem'),hideCursor()" onclick="document.location.href='#'">
                        &nbsp;&nbsp;<a class="footerMenuLink" href="ContactUs.jsp">CONTACT US</a>&nbsp;&nbsp;
                      </td>
                      <td><img src="images/ftrMenuSeparator.gif" width="1" height="16" alt="" /></td>
                      <td align="center" height="20" class="footerMenuItem" onmouseover="changeMenuStyle(this,'footerMenuItemOver'),showCursor()" onmouseout="changeMenuStyle(this,'footerMenuItem'),hideCursor()" onclick="document.location.href='#'">
                        &nbsp;&nbsp;<a class="footerMenuLink" href="PrivacyNotice.jsp">PRIVACY NOTICE</a>&nbsp;&nbsp;
                      </td>
                      <td><img src="images/ftrMenuSeparator.gif" width="1" height="16" alt="" /></td>
                      <td align="center" height="20" class="footerMenuItem" onmouseover="changeMenuStyle(this,'footerMenuItemOver'),showCursor()" onmouseout="changeMenuStyle(this,'footerMenuItem'),hideCursor()" onclick="document.location.href='#'">
                        &nbsp;&nbsp;<a class="footerMenuLink" href="Disclaimer.jsp">DISCLAIMER</a>&nbsp;&nbsp;
                      </td>
                      <td><img src="images/ftrMenuSeparator.gif" width="1" height="16" alt="" /></td>
                      <td align="center" height="20" class="footerMenuItem" onmouseover="changeMenuStyle(this,'footerMenuItemOver'),showCursor()" onmouseout="changeMenuStyle(this,'footerMenuItem'),hideCursor()" onclick="document.location.href='#'">
                        &nbsp;&nbsp;<a class="footerMenuLink" href="Accessibility.jsp">ACCESSIBILITY</a>&nbsp;&nbsp;
                      </td>
                      <td><img src="images/ftrMenuSeparator.gif" width="1" height="16" alt="" /></td>
                      <td align="center" height="20" class="footerMenuItem" onmouseover="changeMenuStyle(this,'footerMenuItemOver'),showCursor()" onmouseout="changeMenuStyle(this,'footerMenuItem'),hideCursor()" onclick="document.location.href='#'">
                        &nbsp;&nbsp;<a class="footerMenuLink" href="ApplicationSupport.jsp">APPLICATION SUPPORT</a>&nbsp;&nbsp;
                      </td>
                    </tr>
                  </table>
                  <!-- application ftr ends -->