<!-- nci hdr begins -->
<tr>
  <td>
    <table width="100%" border="0" cellspacing="0" cellpadding="0" class="hdrBG">
      <tr>
        <td width="283" height="37" align="left"><a href="http://www.cancer.gov"><img alt="National Cancer Institute" src="images/logotype.gif" width="283" height="37" border="0"/></a></td>
        <td>&nbsp;</td>
        <td width="295" height="37" align="right"><a href="http://www.nih.gov/"><img alt="U.S. National Institutes of Health" src="images/tagline.gif" width="295" height="37" border="0"/></a></td>
      </tr>
    </table>
  </td>
</tr>
<!-- nci hdr ends -->