<!-- main menu begins -->
<table summary="" cellpadding="0" cellspacing="0" border="0" height="20">
  <tr>
    <td width="1"><!-- anchor to skip main menu --><a href="#content"><img src="images/shim.gif" alt="Skip Menu" width="1" height="1" border="0" /></a></td>
	<!-- link 1 begins -->
    <td height="20" class="mainMenuItemOver" onmouseover="changeMenuStyle(this,'mainMenuItemOver'),showCursor()" onmouseout="changeMenuStyle(this,'mainMenuItemOver'),hideCursor()" onclick="document.location.href='Home.action'">
      <a class="mainMenuLink" href="Home.action">HOME</a>
    </td>
    <td><img src="images/mainMenuSeparator.gif" width="1" height="16" alt="" /></td>
    <!-- link 1 ends -->
    <td height="20" class="mainMenuItem" onmouseover="changeMenuStyle(this,'mainMenuItemOver'),showCursor()" onmouseout="changeMenuStyle(this,'mainMenuItem'),hideCursor()" onclick="document.location.href='docs'">
      <a class="mainMenuLink" href="docs">JAVA DOCS</a>
    </td>
    <!-- link 2 ends -->
    <td><img src="images/mainMenuSeparator.gif" width="1" height="16" alt="" /></td>
  </tr>
</table>
<!-- main menu ends -->