-- allow FKs to be create on a ContainerType's (ID, SITE_ID)
ALTER TABLE `CONTAINER_TYPE` ADD KEY (`ID`, `SITE_ID`);

-- make it impossible for ContainerType-s to be related to other ContainerType-s
-- if they are not in the same site.
ALTER TABLE `CONTAINER_TYPE_CONTAINER_TYPE` ADD COLUMN `SITE_ID` int(11) NOT NULL;

ALTER TABLE `CONTAINER_TYPE_CONTAINER_TYPE` DROP FOREIGN KEY `FK_PARENT`;
ALTER TABLE `CONTAINER_TYPE_CONTAINER_TYPE` DROP KEY `FK_PARENT`;
ALTER TABLE `CONTAINER_TYPE_CONTAINER_TYPE` DROP FOREIGN KEY `FK_CHILD`;
ALTER TABLE `CONTAINER_TYPE_CONTAINER_TYPE` DROP KEY `FK_CHILD`;

ALTER TABLE `CONTAINER_TYPE_CONTAINER_TYPE` ADD CONSTRAINT `FK_PARENT`
  FOREIGN KEY `FK_PARENT` (`PARENT_CONTAINER_TYPE_ID`, `SITE_ID`)
  REFERENCES `CONTAINER_TYPE` (`ID`, `SITE_ID`);
ALTER TABLE `CONTAINER_TYPE_CONTAINER_TYPE` ADD CONSTRAINT `FK_CHILD`
  FOREIGN KEY `FK_CHILD` (`CHILD_CONTAINER_TYPE_ID`, `SITE_ID`)
  REFERENCES `CONTAINER_TYPE` (`ID`, `SITE_ID`);

-- make it impossible for Container's to have a ContainerType with a different
-- Site
ALTER TABLE `CONTAINER` DROP FOREIGN KEY `FK_CONTAINER_TYPE`;
ALTER TABLE `CONTAINER` DROP KEY `FK_CONTAINER_TYPE`;
ALTER TABLE `CONTAINER` ADD CONSTRAINT `FK_CONTAINER_TYPE`
  FOREIGN KEY `FK_CONTAINER_TYPE` (`CONTAINER_TYPE_ID`, `SITE_ID`)
  REFERENCES `CONTAINER_TYPE` (`ID`, `SITE_ID`);
