CREATE INDEX NUMBER_IDX ON PATIENT(PNUMBER);
CREATE INDEX WAYBILL_IDX ON SHIPMENT_INFO(WAYBILL);
CREATE INDEX RECEIVED_AT_IDX ON SHIPMENT_INFO(RECEIVED_AT);
CREATE INDEX CREATED_AT_IDX ON PROCESSING_EVENT(CREATED_AT);
CREATE INDEX INV_ID_IDX ON SPECIMEN(INVENTORY_ID);
CREATE INDEX PATH_IDX ON CONTAINER(PATH);
