#!/bin/bash

#set -o verbose

ARGS=5
E_BADARGS=85

if [ $# -ne $ARGS ]  # Correct number of arguments passed to script?
then
  echo "Usage: `basename $0` HOST USER PWD DBNAME OUTFILE"
  exit $E_BADARGS
fi

MYSQL=/usr/bin/mysql
SED=/bin/sed
HOST=$1
USER=$2
PWD=$3
DBNAME=$4
OUTPUT=$5

echo "$*" > $OUTPUT
echo "" >> $OUTPUT
echo "---------------------" >> $OUTPUT
echo "" >> $OUTPUT

function mysqlCsv {
    #echo "parms: $*"
    $MYSQL -h$HOST -u$USER -p$PWD -D$DBNAME -B -e "$*" | $SED 's/\t/\",\"/g;s/^/\"/;s/$/\"/;s/\n//g;s/\"NULL\"/null/g' >> $OUTPUT
}

QUERIES[0]="select name, activity_status, comment, street1, street2, city,
province, postal_code from clinic join address on address.id=clinic.address_id
order by clinic.name"

QUERIES[1]="select clinic.name, contact.name, contact.title,
contact.phone_number, contact.fax_number, contact.email_address from clinic
join contact on contact.clinic_id=clinic.id order by clinic.name, contact.name"

QUERIES[2]="select container.label, container.product_barcode,
container.activity_status, container.comment, container.temperature,
abstract_position.row, abstract_position.col from container join
container_position on
container_position.abstract_position_id=container.position_id join
abstract_position on abstract_position.id=container.position_id order by label"

QUERIES[3]="select container_type.name_short, container_type.name, top_level,
default_temperature, comment, activity_status, row_capacity, col_capacity,
container_labeling_scheme.name from container_type join capacity on
capacity.id=container_type.capacity_id join container_labeling_scheme on
container_labeling_scheme.id=container_type.child_labeling_scheme_id order by
container_type.name_short"

QUERIES[4]="select container_type.name_short, parent_ct.name_short from
container_type join (select name_short, child_container_type_id from
container_type join container_type_container_type on
container_type_container_type.parent_container_type_id=container_type.id) as
parent_ct on parent_ct.child_container_type_id=container_type.id order by
container_type.name_short, parent_ct.name_short"

QUERIES[5]="select container_type.name_short, sample_type.name_short from
container_type join container_type_sample_type on
container_type_sample_type.container_type_id=container_type.id join sample_type
on sample_type.id=container_type_sample_type.sample_type_id order by
container_type.name_short"

QUERIES[6]="select name_short, sample_source.name from study join
study_sample_source on study_sample_source.study_id=study.id join sample_source
on sample_source.id=study_sample_source.sample_source_id order by name_short,
sample_source.name"

QUERIES[7]="select study.name_short, sample_type.name_short, quantity, volume
from study join sample_storage on sample_storage.study_id=study.id join
sample_type on sample_type.id=sample_storage.sample_type_id order by
study.name_short, sample_type.name_short"

QUERIES[8]="select name, name_short from sample_type order by name"

QUERIES[9]="select name, name_short, activity_status, comment from study order by name"

QUERIES[10]="select name_short, contact.name, clinic.name from study join
study_contact on study_contact.study_id=study.id join contact on
contact.id=study_contact.contact_id join clinic on clinic.id=contact.clinic_id
order by name_short, contact.name, clinic.name"

for qry in "${QUERIES[@]}"
do
    echo "$qry" >> $OUTPUT
    echo "" >> $OUTPUT
    mysqlCsv $qry
    echo "" >> $OUTPUT
    echo "---------------------" >> $OUTPUT
    echo "" >> $OUTPUT
done
