#!/bin/bash

#set -o verbose

ARGS=5
E_BADARGS=85

if [ $# -ne $ARGS ]  # Correct number of arguments passed to script?
then
  echo "Usage: `basename $0` USER HOST PWD DBNAME OUTFILE"
  exit $E_BADARGS
fi

MYSQL=/usr/bin/mysql
SED=/bin/sed
HOST=$1
USER=$2
PWD=$3
DBNAME=$4
OUTPUT=$5

echo "" > $OUTPUT

function mysqlCsv {
    echo "parms: $*"
    $MYSQL -u$USER -p$PWD -D$DBNAME -B -e "$*" | $SED 's/\t/\",\"/g;s/^/\"/;s/$/\"/;s/\n//g;s/\"NULL\"/null/g' >> $OUTPUT
}

QUERIES[0]="select clinic.name, clinic.activity_status, clinic.comment, address.street1, address.street2, address.city,
address.province, address.postal_code from clinic join address on address.id=clinic.address_id order by clinic.name"

QUERIES[1]="select clinic.name, contact.name, contact.title, contact.phone_number, contact.fax_number,
contact.email_address from clinic join contact on contact.clinic_id=clinic.id order by clinic.name, contact.name"

for qry in "${QUERIES[@]}"
do
    mysqlCsv $qry
    echo "" >> $OUTPUT
done
