#!/bin/bash

#set -o verbose

ARGS=3
E_BADARGS=85

if [ $# -lt $ARGS ]  # Correct number of arguments passed to script?
then
  echo "Usage: `basename $0` HOST USER PWD [DBNAME] "
  exit $E_BADARGS
fi

MYSQLDUMP="/usr/bin/mysqldump"

HOST=$1
USER=$2
PWD=$3
DBNAME=$4

# tables to skip
skip_tables=(csm_application csm_filter_clause csm_group csm_pg_pe csm_privilege csm_protection_element csm_protection_group csm_role csm_role_privilege csm_user csm_user_group csm_user_group_role_pg csm_user_pe log_message object_attribute objectattributes )

if [ -z "$DBNAME" ]; then
    DBNAME=biobank2
fi

OPTS=
n=${#skip_tables[@]}
for (( i = 0; i < n; i++ )) do
        OPTS[$i]="--ignore-table=${DBNAME}.${skip_tables[$i]}"
done

$MYSQLDUMP ${OPTS[*]} -h$HOST -u$USER -p$PWD $DBNAME | gzip > ${DBNAME}_`date +%y_%m_%d`.sql.gz
