#!/bin/bash

#set -o verbose

ARGS=6
E_BADARGS=85

if [ $# -ne $ARGS ]  # Correct number of arguments passed to script?
then
  echo "Usage: `basename $0` HOST USER PWD DBNAME SITE_NAME OUTFILE"
  exit $E_BADARGS
fi

MYSQL=/usr/bin/mysql
SED=/bin/sed
HOST=$1
USER=$2
PWD=$3
DBNAME=$4
SITE_NAME=$5
OUTPUT=$6
COUNTER=1

function mysqlCsv {
    #echo "parms: $*"
    $MYSQL -h$HOST -u$USER -p$PWD -D$DBNAME -B -e "$*" | $SED 's/\t/\",\"/g;s/^/\"/;s/$/\"/;s/\n//g;s/\"NULL\"/null/g' >> $COUNTER$OUTPUT
}

QUERIES[0]="select clinic.name, clinic.name_short,clinic.sends_shipments,clinic.activity_status_id,
street1, street2, city,province, postal_code
from center clinic
join address on address.id=clinic.address_id
where discriminator='Clinic'
order by clinic.name"

QUERIES[1]="select clinic.name_short, contact.name, contact.title,
contact.office_number, contact.fax_number, contact.email_address
from center clinic
join contact on contact.clinic_id=clinic.id
where discriminator='Clinic'
order by clinic.name, contact.name"

QUERIES[2]="select container.label, container.product_barcode,
container.activity_status_id, container.temperature,
container_type.name_short
from container
join container_type on container_type.id=container.container_type_id
join center site on site.id=container.site_id
where site.name_short='$SITE_NAME'
order by label"

QUERIES[3]="select container_type.name,  container_type.name_short, top_level,
default_temperature, container_type.activity_status_id, row_capacity, col_capacity,
container_labeling_scheme.name from container_type
join container_labeling_scheme on container_labeling_scheme.id=container_type.child_labeling_scheme_id
join center site on site.id=container_type.site_id
where site.name_short='$SITE_NAME'
order by container_type.name_short"

QUERIES[4]="select container_type.name_short, parent_ct.name_short
from container_type
join (select name_short, child_container_type_id from
container_type join container_type_container_type on
container_type_container_type.parent_container_type_id=container_type.id) as
parent_ct on parent_ct.child_container_type_id=container_type.id
join center site on site.id=container_type.site_id
where site.name_short='$SITE_NAME'
order by container_type.name_short, parent_ct.name_short"

QUERIES[5]="select container_type.name_short, specimen_type.name_short
from container_type
join container_type_specimen_type on container_type_specimen_type.container_type_id=container_type.id
join specimen_type on specimen_type.id=container_type_specimen_type.specimen_type_id
join center site on site.id=container_type.site_id
where site.name_short='$SITE_NAME'
order by container_type.name_short,specimen_type.name_short"

QUERIES[6]="select study.name_short, st.name
from study
join source_specimen on source_specimen.study_id=study.id
join specimen_type st on st.id=source_specimen.specimen_type_id
order by name_short,st.name"

QUERIES[7]="select study.name_short, specimen_type.name_short, quantity, volume
from study
join aliquoted_specimen on aliquoted_specimen.study_id=study.id
join specimen_type on specimen_type.id=aliquoted_specimen.specimen_type_id
order by study.name_short, specimen_type.name_short"

QUERIES[8]="select name, name_short from specimen_type order by name"

QUERIES[9]="select study.name, study.name_short, study.activity_status_id
from study
order by study.name"

QUERIES[10]="select study.name_short, contact.name, clinic.name_short
from study
join study_contact on study_contact.study_id=study.id
join contact on contact.id=study_contact.contact_id
join center clinic on clinic.id=contact.clinic_id
order by study.name_short, contact.name, clinic.name_short"

for qry in "${QUERIES[@]}"
do
    #echo "$qry" >> $COUNTER$OUTPUT
    mysqlCsv $qry
    COUNTER=$[COUNTER + 1]
done
