#!/bin/bash

#set -o verbose

SCRIPT=`basename $0`

USAGE="
Usage: $SCRIPT [OPTIONS]

OPTIONS
  -d DUMP     The original biobank database dump file name compressed with gzip. Optional.
  -H DBHOST   The hostname of the machine running the MySQL server. Defaults to
              localhost if not specified.
  -n DBNAME   The name of the database. If it exists it is first DROPPED.
  -u DBUSER   The user to use on the MySQL server. Optional.
  -h          Help text.
"

MYSQL=/usr/bin/mysql
MYSQLDUMP=/usr/bin/mysqldump
SED=/bin/sed
DBHOST="localhost"
DBNAME="biobank"
OSTYPE=`uname -s | tr [:upper:] [:lower:]`

while getopts "d:hH:n:u:p:o:" OPTION
do
    case $OPTION in
        d) DBDUMP=$OPTARG
            shift $((OPTIND-1)); OPTIND=1
            ;;
        H) DBHOST=$OPTARG
            shift $((OPTIND-1)); OPTIND=1
            ;;
        n) DBNAME=$OPTARG
            shift $((OPTIND-1)); OPTIND=1
            ;;
        u) DBUSER=$OPTARG
            shift $((OPTIND-1)); OPTIND=1
            ;;
        p) DBPWD=$OPTARG
            shift $((OPTIND-1)); OPTIND=1
            ;;
        h) echo "$USAGE"; exit;;
    esac
done


if [ -z "$DBUSER" ]; then
    read -p "MySQL user on host $DBHOST: " DBUSER
fi

if [ -z "$DBUSER" ]; then
    echo "ERROR: user not specified"
    exit
fi

if [ -z "$DBPWD" ]; then
    read -s -p "MySQL Password for user $DBUSER: " DBPWD
    echo ""
fi

if [ -z "$DBPWD" ]; then
    echo "ERROR: password not specified"
    exit
fi

if [ -z "$DBDUMP" ]; then
    read -p "MySQL database dump (gzipped): " DBDUMP
fi

eval DBDUMP=$DBDUMP

if [ -z "$DBDUMP" ]; then
    echo "ERROR: old database dump not specified"
    exit
fi

if [ ! -f "$DBDUMP" ]; then
    echo "ERROR: database dump file does not exist"
    exit
fi

DUMPFILE="/tmp/$SCRIPT.$RANDOM.sql"

echo "recreating database..."
mysqladmin -f -h$DBHOST -u$DBUSER -p$DBPWD drop $DBNAME
mysqladmin -h$DBHOST -u$DBUSER -p$DBPWD create $DBNAME
echo "importing old database..."
if [ $OSTYPE == 'linux' ]; then
    pv $DBDUMP | gzip -dc | mysql -h$DBHOST -u$DBUSER -p$DBPWD $DBNAME
else
    gzip -dc $DBDUMP | mysql -h$DBHOST -u$DBUSER -p$DBPWD $DBNAME
fi
echo "upgrading database..."
mysql -h$DBHOST -u$DBUSER -p$DBPWD $DBNAME < data/sql/upgrade_v321_v330.sql
echo "done"
