#!/bin/bash

#set -o verbose

SCRIPT=`basename $0`

USAGE="
Usage: $SCRIPT [OPTIONS]

OPTIONS
  -d DUMP     The original biobank2 database dump file name.
  -H DBHOST   The hostname of the machine running the MySQL server. Defaults to
              localhost if not specified.
  -u DBUSER   The user to use on the MySQL server.
  -p PWD      The password to use on the MySQL server.
  -h          Help text.
"

MYSQL=/usr/bin/mysql
MYSQLDUMP=/usr/bin/mysqldump
SED=/bin/sed
DBHOST="localhost"
DBNAME=biobank2

while getopts "e:d:hH:u:p:o:" OPTION
do
  case $OPTION in
        d) DBDUMP=$OPTARG;;
        H) DBHOST=$OPTARG;;
        u) DBUSER=$OPTARG;;
        p) DBPWD=$OPTARG;;
        h) echo "$USAGE"; exit;;
  esac
done

if [ -z "$DBDUMP" ]; then
    echo "ERROR: old database dump not specified"
    echo "$USAGE"
    exit
fi

if [ -z "$DBUSER" ]; then
    echo "ERROR: user not specified"
    echo "$USAGE"
    exit
fi

if [ -z "$DBPWD" ]; then
    echo "ERROR: password not specified"
    echo "$USAGE"
    exit
fi

DUMPFILE="/tmp/$SCRIPT.$RANDOM.sql"

echo "recreating database..."
mysqladmin -f -h$DBHOST -u$DBUSER -p$DBPWD drop biobank2
mysqladmin -f -h$DBHOST -u$DBUSER -p$DBPWD drop biobank
mysqladmin -f -h$DBHOST -u$DBUSER -p$DBPWD create biobank
mysql -h$DBHOST -u$DBUSER -p$DBPWD  biobank -e "grant all privileges on biobank.* to 'dummy'@'localhost' with grant option"
if [ -s /usr/bin/pv ]; then
    pv $DBDUMP | gzip -dc | mysql -h$DBHOST -u$DBUSER -p$DBPWD biobank
else
    gzip -dc $DBDUMP | mysql -h$DBHOST -u$DBUSER -p$DBPWD biobank
fi
echo "upgrading database from v3.0.2 to v3.1.0 ..."
mysql -h$DBHOST -u$DBUSER -p$DBPWD biobank < data/sql/upgrade_v302_v310.sql
echo "upgrading database from v3.1.0 to v3.2.0 ..."
mysql -h$DBHOST -u$DBUSER -p$DBPWD biobank < data/sql/upgrade_v310_v320.sql
echo "assigning groups..."
mysql -h$DBHOST -u$DBUSER -p$DBPWD biobank < db/import/data/groups.sql
echo "migrating security..."
mysql -h$DBHOST -u$DBUSER -p$DBPWD biobank < data/sql/upgrade_v310_v320_security_transfer.sql
echo "upgrading database from v3.2.0 to v3.2.1 ..."
mysql -h$DBHOST -u$DBUSER -p$DBPWD biobank < data/sql/upgrade_v320_321.sql
echo "upgrading database from v3.2.1 to v3.3.0 ..."
mysql -h$DBHOST -u$DBUSER -p$DBPWD biobank < data/sql/upgrade_v321_v330.sql
