#!/bin/bash

#set -o verbose

SCRIPT=`basename $0`

USAGE="
Usage: $SCRIPT [OPTIONS]

OPTIONS
  -e TABLE    Exclude table with name TABLE. This option can be used multiple
              times to exclude multiple tables.
  -d DUMP     The biobank2 database dump file name.
  -H DBHOST   The hostname of the machine running the MySQL server. Defaults to
              localhost if not specified.
  -u DBUSER   The user to use on the MySQL server.
  -p PWD      The password to use on the MySQL server.
  -h          Help text.
"

MYSQL=/usr/bin/mysql
MYSQLDUMP=/usr/bin/mysqldump
SED=/bin/sed
DBHOST="localhost"
DBNAME=biobank2

while getopts "e:d:hH:u:p:o:" OPTION
do
  case $OPTION in
        e) exclude=(${exclude[@]} $OPTARG );;
        d) DBDUMP=$OPTARG;;
        H) DBHOST=$OPTARG;;
        u) DBUSER=$OPTARG;;
        p) DBPWD=$OPTARG;;
        h) echo "$USAGE"; exit;;
  esac
done


if [ -z "$DBUSER" ]; then
    echo "ERROR: user not specified"
    echo "$USAGE"
    exit
fi

if [ -z "$DBPWD" ]; then
    echo "ERROR: password not specified"
    echo "$USAGE"
    exit
fi

DUMPFILE="/tmp/$SCRIPT.$RANDOM.sql"

ant dbcreate
scripts/dump_csm_schema.sh -ecsm_user -H$DBHOST -u$DBUSER -p$DBPWD -o$DUMPFILE
gzip -dc $DBDUMP | mysql -h$DBHOST -u$DBUSER -p$DBPWD biobank2
mysql -h$DBHOST -u$DBUSER -p$DBPWD biobank2 < data/sql/upgrade_v123_v130.sql
mysql -h$DBHOST -u$DBUSER -p$DBPWD biobank2 < $DUMPFILE
mysql -h$DBHOST -u$DBUSER -p$DBPWD biobank2 < security-logs/schemaLog.sql
