#!/bin/bash

#set -o verbose

SCRIPT=`basename $0`

USAGE="
Usage: $SCRIPT [OPTIONS]

OPTIONS
  -d DUMP     The original biobank database dump file name.
  -H DBHOST   The hostname of the machine running the MySQL server. Defaults to
              localhost if not specified.
  -u DBUSER   The user to use on the MySQL server.
  -p PWD      The password to use on the MySQL server.
  -h          Help text.
"

MYSQL=/usr/bin/mysql
MYSQLDUMP=/usr/bin/mysqldump
SED=/bin/sed
DBHOST="localhost"
OSTYPE=`uname -s | tr [:upper:] [:lower:]`

while getopts "d:hH:u:p:o:" OPTION
do
    case $OPTION in
        d) DBDUMP=$OPTARG
            shift $((OPTIND-1)); OPTIND=1
            ;;
        H) DBHOST=$OPTARG
            shift $((OPTIND-1)); OPTIND=1
            ;;
        u) DBUSER=$OPTARG
            shift $((OPTIND-1)); OPTIND=1
            ;;
        p) DBPWD=$OPTARG
            shift $((OPTIND-1)); OPTIND=1
            ;;
        h) echo "$USAGE"; exit;;
    esac
done

if [ -z "$DBDUMP" ]; then
    echo "ERROR: old database dump not specified"
    echo "$USAGE"
    exit
fi

if [ -z "$DBUSER" ]; then
    echo "ERROR: user not specified"
    echo "$USAGE"
    exit
fi

if [ -z "$DBPWD" ]; then
    echo "ERROR: password not specified"
    echo "$USAGE"
    exit
fi

DUMPFILE="/tmp/$SCRIPT.$RANDOM.sql"

echo "recreating database..."
mysqladmin -f -h$DBHOST -u$DBUSER -p$DBPWD drop biobank create biobank
echo "importing old database..."
if [ $OSTYPE == 'linux' ]; then
    pv $DBDUMP | gzip -dc | mysql -h$DBHOST -u$DBUSER -p$DBPWD biobank
else
    gzip -dc $DBDUMP | mysql -h$DBHOST -u$DBUSER -p$DBPWD biobank
fi
echo "upgrading database..."
mysql -h$DBHOST -u$DBUSER -p$DBPWD biobank < data/sql/upgrade_v320_321.sql
echo "done"
