#!/bin/bash

#
# Biobank TEMPORARY THROW-AWAY TEST key
#
#

if [[ -z "$JAVA_HOME" ]]; then
   echo "Error: environment variable JAVA_HOME is not assigned"
   exit 1
fi

if [[ ! -f "$JAVA_HOME/bin/java" ]]; then
   echo "Error: Java JRE not found at $JAVA_HOME"
   exit 1
fi

if [[ ! -d "tools" ]]; then
   echo "Error: tools directory not found."
   exit 1
fi

if [[ ! -d "$HOME/jboss-4.0.5.GA" ]]; then
   echo "Error: JBoss directory not found in home directory."
   exit 1
fi

JAVA="$JAVA_HOME/bin/java"
KEYTOOL="$JAVA_HOME/jre/bin/keytool"
SED=/bin/sed
OPENSSL=/usr/bin/openssl
DFLT_DNAME_CN="localhost"
CERT_CNF_FNAME=`tempfile`
CERT_DER_FNAME=`tempfile`
KEY_DER_FNAME=`tempfile`

echo "This script generates a TEMPORARY THROW-AWAY TEST key."
echo "It is not recommended to use this key in a production environment!"
echo ""

# this command could return multiple IP addresses, we will just use the first one
IN=`hostname -I`
IP_ADDRS=(${IN//;/ }) # split the result using space as a delimiter
DFLT_SUBJ_ALT_NAME="IP:${IP_ADDRS[0]},DNS:localhost"

read -p "Enter CN: [$DFLT_DNAME_CN] " DNAME_CN
DNAME_CN=${DNAME_CN:-$DFLT_DNAME_CN}

read -p "Enter subjectAltName: [$DFLT_SUBJ_ALT_NAME] " SUBJ_ALT_NAME
SUBJ_ALT_NAME=${SUBJ_ALT_NAME:-$DFLT_SUBJ_ALT_NAME}

read -p "Enter an alias: [$DNAME_CN] " KEYSTORE_ALIAS
KEYSTORE_ALIAS=${KEYSTORE_ALIAS:-$DFLT_DNAME_CN}

$SED "s/@@dName.CN@@/$DNAME_CN/g;s/@@subjectAltName@@/$SUBJ_ALT_NAME/g" templates/cert.cnf.template > $CERT_CNF_FNAME

$OPENSSL req -newkey rsa:1024 -x509 -outform DER -out $CERT_DER_FNAME -days 3650 -config $CERT_CNF_FNAME
$OPENSSL pkcs8 -topk8 -nocrypt -in key.pem -inform PEM -out $KEY_DER_FNAME -outform DER
$JAVA -cp tools -Dkeystore=biobank.keystore ImportKey $KEY_DER_FNAME $CERT_DER_FNAME $KEYSTORE_ALIAS
$KEYTOOL -keystore biobank.keystore -alias $KEYSTORE_ALIAS -storepass importkey -keypasswd -keypass importkey -new biobank2
$KEYTOOL -keystore biobank.keystore -storepasswd -storepass importkey -new biobank2
mv biobank.keystore jboss-4.0.5.GA/server/default/conf
rm key.pem
