				<!-- application hdr begins -->
				<tr>
					<td height="50">
						<table width="100%" height="50" border="0" cellspacing="0" cellpadding="0" class="subhdrBG">
							<tr>
								<td height="50" align="left"><a href="#"><img src="images/sdkLogoSmall.gif" alt="Application Logo" hspace="10" border="0"/></a></td>
							</tr>
						</table>
					</td>
				</tr>
				<!-- application hdr ends -->